name: linux-x64

on:
  push:
    branches:
      - winport
      - openfst-1.8.5

  pull_request:
    branches:
      - winport
      - openfst-1.8.5

  workflow_dispatch:

concurrency:
  group: linux-x64-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux_x64:
    name: Linux x64 (${{ matrix.build_type }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: |
          cmake --version
          g++ --version

          cmake -S. -Bbuild -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX="$PWD/build/install"

      - name: Build openfst for Linux x64
        run: |
          cmake --build build --parallel
          cmake --build build --target install

      - name: Verify install
        run: |
          ls -lh build/install/bin/fstinfo
